### ISSUE TITLE
[mi] Filter out English text

### ISSUE THREAD

**Issue by brawer** [googlei18n/corpuscrawler#26]
The crawled Maori language corpus contains some English text. By filtering out every paragraph that contains the string ` the `, we’d remove 1902 lines from the corpus which are mostly English-language quotes. I believe this would be an improvement. @jimregan, would you be fine with this change?

Here’s a few sample paragraphs that would be removed:

> Hei tā Whakaruru, “That's what the King believed his mother signed was to give us the means to help. We want to put on the table lands, resources and people.”

> The doting parents of Whakatōhea descendant Kayla Imrie have won a free ticket to the Olympics.

> Hei tā Kiripatea, “This is a primary model of one of the backyard gardens that we have done and we did it over a weekend.”

> Thanks to Volkswagen, they will get a free ticket to watch their daughter perform with the NZ K4 Women's Kayaking crew at Rio.

> The first-time Olympian is currently in Portugal training alongside her K4 team, Aimee Fisher, Caitlin Ryan and Jamie Lovett, for the upcoming world cup in Germany this month.

> Ko tā Marama Davidson, mema o te Pāti Kākāriki, “We are still in decline when it comes to those who can speak te reo. So I think it's only 3.7% of people in Aotearoa can have a conversation in te reo. We know that over 77% of children are not enrolled in any subject at schools at the moment and we know that half of all schools in Aotearoa have absolutely no student learning te reo or taking a te reo subject.”

**Comment by jimregan** [comment]
Fine by me.
